version: "3.8"

services:
  accounts-service:
    build: ./services/accounts-service
    container_name: accounts-service
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: password
      DB_NAME: backstack_accounts
    networks:
      - backstack-net

  schema-service:
    build: ./services/schema-service
    container_name: schema-service
    restart: always
    depends_on:
      - db
      - redis
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: password
      DB_NAME: backstack_schema
      REDIS_URL: redis://redis:6379
    networks:
      - backstack-net

  crud-service:
    build: ./services/crud-service
    container_name: crud-service
    restart: always
    depends_on:
      - db
      - redis
      - schema-service
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/backstack_schema
      REDIS_URL: redis://redis:6379
      PORT: 4001
      DB_SSL: "false"
    ports:
      - "4001:4001"   # optional: expose for testing; can be removed in prod
    networks:
      - backstack-net

  client-service:
    build: ./services/client-service
    container_name: client-service
    restart: always
    ports:
      - "5173:5173"
  api-gateway:
    build: ./infra/nginx
    container_name: api-gateway
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - accounts-service
      - schema-service
      - crud-service
    networks:
      - backstack-net

  db:
    image: postgres:15
    container_name: backstack-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: backstack_accounts   
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backstack-net

  redis:
    image: redis:7-alpine
    container_name: backstack-redis
    restart: always
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    ports:
      - "6379:6379"   # optional, can be removed if only internal
    volumes:
      - redis-data:/data
    networks:
      - backstack-net

networks:
  backstack-net:
    driver: bridge

volumes:
  db-data:
  redis-data:
